colorme/colorme.py
colorme/info.json

code rewritten to work better on large servers.
no longer limited to a default role.
new role is created as a copy of top_role

colorme rewrite

---

blizzard/blizzard.py

I used your code to display the current wow token price on NA. 
You can try it out on my fork too. 
I thought you might want to integrate it. 
Sorry if it's not elegant, I'm extremely new to all this. 
Have a great day.

Display wowtoken.info  current NA stats

---

smartreact/smartreact.py

This should allow the bot to use smartreact with any custom emoji (like those provided by bttv) from any server the bot is connected to.

Smartreact custom emoji from any server

---

README.md
sfx/info.json
sfx/sfx.py

hang on to your knickers.... here we go.... sfx when?

merging sfx into master

---

spoiler/spoiler.py

Make the spoiler text much more easier on our eyes

spoiler font color change

---

smite/info.json
smite/smite.py

This is long overdue. With these updates, API sessions are now opened/managed automatically, and the cog is ready for release.

merge smite into master branch

---

blizzard/blizzard.py
blizzard/info.json

byebye Pandoc! Helllooo cool new patch notes with reaction navigation!
and some Overwatch stats bug fixes as well.

Blizzard rewrite

---

sfx/sfx.py

Substantial improvements to sfx queuing. Queue is now available for use by other cogs.

Sfx async queue merge

---

README.md
blizzard/blizzard.py

Cog is no longer hard-coded for the US API. All regions should work now!
Also sneaking in a readme update 😉

[Blizzard] Add multi-region support for Diablo 3 stats

---

spoiler/spoiler.py

also opinionated formatting... sorry

[spoiler] fix \n and indent eating.

---

blizzard/blizzard.py

It works for US region because it's hard coded. 
Could use a little help on making it dynamic toward localization and actually pulling the time last updated.
Or we could use JSON files from the following site but I'm inexperienced. 
http://wowtokenprices.com/data

[Blizzard] Changed WoW Token Info Source.

---

wordcloud/info.json
wordcloud/wordcloud.py

Merge v2 WordCloud cog written by FlapJack and aikaterna.

[WordCloud] add WordCloud cog

---

README.md
wordcloud/wordcloud.py

The wordcloud image can now be customized on each server, by mod role and above. (Image uploads are still owner only)

[wordcloud] implement server specific image settings

---

cryptoprice/cryptoprice.py

Coinmarketcap changed their website. This fixes it.

This fixes the script

---

blizzard/blizzard.py
cryptoprice/cryptoprice.py
dongers/dongers.py
sfx/sfx.py
wordcloud/wordcloud.py

I hope this fixie wixie will fix the fucky wucky deprecated aiohttp function.
Pwease review and merge

Fixie wixie for woopsie on pwevious PR attempt

---

wordclouds/wordclouds.py

self.bot.say -> ctx.send, no context needed, no_pm -> commands.guild_only

[V3 Wordclouds] V3 updates

---

smartreact/smartreact.py

Add listreact command to show reactions in the current guild, removed v2 code, added some exceptions for bad emojis or if the message already has 20 reactions and the bot is blocked from adding more.

[V3 SmartReact] Add listreact, remove v2 remnants

---

blizzard/blizzard.py
colorme/colorme.py
smite/smite.py
wat/wat.py
wordclouds/wordclouds.py

this fix the double sending of help

colorme group command help fix

---

cryptoprice/__init__.py
cryptoprice/cryptoprice.py
cryptoprice/info.json

Scans first 10 pages of CMC and also shows price in BTC

Updated cryptoprice to v3

---

msgvote/msgvote.py

Changed the global config to guild-based config. Also added a current settings display when msgvote is used with no argument. Removed _fix_defaults as it was not needed.

[V3 Msgvote] Global Config -> guild Config

---

colorme/colorme.py
msgvote/msgvote.py
wat/wat.py

Changed manage_server to manage_guild so that they work with the latest version of Red

Red v3 rewrites

---

reactpoll/reactpoll.py

Added some (shit) code to allow for Tie conditions and polls where no one votes.

Added TIES and No-Votes
